module7-task1
htmlacademy-javascript/997093-keksobooking-23 pull request #5
Opened 2021-06-17 16:56 UTC by kildim

2021-06-17 17:00 UTC, kildim commented on js/utils/mathematics.js
> +function arraysIntersection (array1, array2) {
Функция не используется в коде. Решил оставить, вдруг пригодится для какой-нибудь будущей задачи в проекте. Жаль удалять, задача-то типовая!

2021-06-17 17:01 UTC, kildim commented on js/utils/mathematics.js
> +function isArraysIntersecting (array1, array2) {
Функция не используется в коде. Решил оставить, вдруг пригодится для какой-нибудь будущей задачи в проекте. Жаль удалять.

2021-06-17 17:02 UTC, kildim commented on js/main.js
> +const ADS_COUNT = 1;
Количество генерируемых рекламных объявлений.

2021-06-17 17:08 UTC, kildim commented on js/utils/data-factories.js
> +const HOSTS_DICTIONARY = new Map([
Немного усложнил инициализацию константы. Ключи для значений задаются через поиск в FEATURE_VALUES. Хотел показать жёсткую смысловую связь констант HOSTS_DICTIONARY и FEATURE_VALUES, что изменение одной из них должно непременно вызвать изменения в другой.

2021-06-18 15:47 UTC, babtshe requested changes

2021-06-18 15:47 UTC, babtshe commented on js/main.js
> +const ADS_COUNT = 1;
сгенерировать нужно все десять, но показать только одно.

2021-06-18 15:47 UTC, babtshe commented on js/main.js
> +});
по хорошему для показа объявления сделать отдельную функцию, но пока можно и так.

2021-06-18 15:47 UTC, babtshe commented on js/markup-generators/card.js
> +const genArticle = (ad) => {
см [критерий](https://up.htmlacademy.ru/javascript/23/criteries#b4)

2021-06-18 15:47 UTC, babtshe commented on js/markup-generators/card.js
> +  ad.offer.title === '' ? popupTitle.classList.add('hidden') : popupTitle.textContent = ad.offer.title;
есть смысл глянуть [критерий](https://up.htmlacademy.ru/javascript/23/criteries#d16). Формально он не совсем про это, но поможет сократить условия.

Кроме того, вместо того, чтобы в каждом условии добавлять класс, есть смысл подумать как можно избавиться от повторяющегося кода.

2021-06-18 15:47 UTC, babtshe commented on js/markup-generators/card.js
> +    popupTextCapacity.textContent = `Заезд после ${ad.offer.checkin}, выезд до ${ad.offer.checkout}`;
количество комнат и гостей потерялось: 
![image](https://user-images.githubusercontent.com/30229773/122583777-481a7d00-d062-11eb-875a-9373df91aa40.png)

2021-06-18 15:47 UTC, babtshe commented on js/utils/data-factories.js
> +const HOSTS_DICTIONARY = new Map([
Стоит учесть, что ты ищешь по массиву-константе. Это значит, что в ходе выполнения программы он не изменится, а вот поиск будет проходить по нему при каждом обращении. Таким образом мы жертвуем производительностью. 

В данном случае для хранения пар ключ-значение дешевле будет использовать просто объект:
```
const whateverValues = {
  a: 'alpha',
  b: 'bravo',
  c: 'charlie',
};
console.log(whateverValues['a']);
```

2021-06-18 15:47 UTC, babtshe commented on js/utils/data-factories.js
> +export {mockAd, FEATURE_VALUES, RESIDENCE_TYPES, HOSTS_DICTIONARY};
обрати внимание, что через какое-то время тестовые данные мы нещадно выпилим и заменим на ответ сервера, а вот типы помещений и прочие константы останутся неизменными. 

Поэтому стоит уже сейчас планировать архитектуру так, чтобы удалить тестовые данные было легко. По хорошему никто, кроме модуля работы с данными не должен знать, что данные не настоящие.

2021-06-18 15:47 UTC, babtshe commented on js/utils/helpers.js
> +export {isOfferFeaturesIntersectingElementClasses};
в качестве альтернативы поиску по массивам можно сразу заполнить контейнер элементами с нужными классами. Но можно оставить и так.

2021-06-18 15:47 UTC, babtshe commented on js/utils/mathematics.js
> +function arraysIntersection (array1, array2) {
гит всё помнит, так что можно смело удалять. Тем более есть такой [критерий](https://up.htmlacademy.ru/javascript/23/criteries#b12).

2021-06-19 14:32 UTC, babtshe requested changes

2021-06-19 14:32 UTC, babtshe commented on js/main.js
> +const cards = advertisements.map(generateArticle);
а если данных будет много? Лучше не хранить в памяти эти карточки, так как они вполне могут не понадобиться, а генерировать по запросу.

2021-06-19 14:32 UTC, babtshe commented on js/markup-generators/card.js
> +  popupTextPrice.textContent = price ? `${price} ₽/ночь` : popupTextPrice.remove();
стоит учесть, что цена может быть '0', в этом случае как раз проверку стоило бы оставить.

2021-06-19 14:32 UTC, babtshe commented on js/markup-generators/card.js
> +  popupTextCapacity.textContent = rooms && guests ? `${rooms} комнаты для ${guests} гостей` :
хорошо бы менять окончания слов в зависимости от числа комнат и гостей.

2021-06-19 14:32 UTC, babtshe commented on js/utils/mathematics.js
>  function getRandomPositiveFloat (arg1, arg2, digits = 1) {
полезные комментарии вполне можно оставлять.

2021-06-20 08:42 UTC, babtshe requested changes

2021-06-20 08:42 UTC, babtshe commented on js/main.js
> +}
в чём польза этого изменения?

2021-06-20 08:42 UTC, babtshe commented on js/markup-generators/card.js
> +  popupTextPrice.textContent = price ? `${price} ₽/ночь` : '0 ₽/ночь';
"цена не указана" и "0" - это не одно и то же.

2021-06-20 08:42 UTC, babtshe commented on js/utils/helpers.js
> +function declOfNum(number, titles) {
хорошо бы поправить имя переменной в соответствии с критериями.

2021-06-20 08:42 UTC, babtshe commented on js/utils/helpers.js
> +  return titles[ (number%100>4 && number%100<20)? 2 : cases[(number%10<5)?number%10:5] ];
обрати внимание на форматирование.

2021-06-20 08:42 UTC, babtshe commented on js/markup-generators/card.js
> +  popupTextCapacity.textContent = rooms && guests ? `${rooms} ${declOfNum(rooms, ['комната', 'комнаты', 'комнат'])} для ${guests} ${declOfNum(guests, ['гость', 'гостя', 'гостей'])}` :
с гостями не всё так просто, см в [ТЗ](https://up.htmlacademy.ru/javascript/23/project/keksobooking#keksobooking-3-6)

2021-06-22 06:44 UTC, babtshe approved these changes

2021-06-22 06:45 UTC, merged